### ISSUE TITLE
TypeError: Cannot read property 'n-ui' of undefined

### ISSUE THREAD

**Issue by sjparkinson** [whitesource/npm-plugin#18]
We're seeing the following in our CircleCI build.

```
OK: Config file is located in: ./whitesource.config.json
OK: Running whitesource...
OK: Done calculation dependencies!
OK: Building dependencies report
INFO: Missing : express-handlebars
TypeError: Cannot read property 'n-ui' of undefined
    at eval (eval at WsNodeReportBuilder.traverseLsJson (/home/ubuntu/next-stream-page/node_modules/whitesource/bin/ws_node_report_builder.js:212:14), <anonymous>:1:46)
    at Object.WsNodeReportBuilder.traverseLsJson (/home/ubuntu/next-stream-page/node_modules/whitesource/bin/ws_node_report_builder.js:212:14)
    at buildReport (/home/ubuntu/next-stream-page/node_modules/whitesource/bin/whitesource.js:194:40)
    at /home/ubuntu/next-stream-page/node_modules/whitesource/bin/whitesource.js:244:16
    at /home/ubuntu/next-stream-page/node_modules/shelljs/src/exec.js:107:7
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by AsafSavichWs** [comment]
Hi,

Thanks for your feedback.
Please make sure you are on the latest WhiteSource version (1.0.7).
If so, please contact support@whitesourcesoftware.com with the following log, and please attach all ws-log-* files in your project directory.

Thanks again!
