### ISSUE TITLE
Issues running under latest node.js LTS 8.9.3 npm 5.5.1 with private npm registry

### ISSUE THREAD

**Issue by anwalkers** [whitesource/npm-plugin#21]
I have a private npm registry that caches public packages and have npm configured to look at my private registry. When I run whitesource I get an error output from the process, but it still successfully publishes my whitesource results. 

Here is and example Error I am getting. I am getting one error entry for each package in my package.json...

```
Error: URL: https://acme.pkgs.visualstudio.com/_packaging/Itron.Cloud.Ipl/npm/registry/@angular%2Fhttp?5.0.5
Error:  Unauthorized
    at C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\bin\ws_node_report_builder.js:280:15
    at tryCatcher (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\bluebird\js\release\promise.js:638:18)
    at Request._callback (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\bluebird\js\release\nodeback.js:42:21)
    at Request.self.callback (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\anwalker\AppData\Roaming\npm\node_modules\whitesource\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by anwalkers** [comment]
I have validated that the error goes away when I downgrade to node.js 6.x. It errors in the 8.x LTS version.

I commented out the console.error in the ws_node_report_builder.js and console errors go away, but I wonder if it is reporting the right information to whitesource...

**Comment by strtdusty** [comment]
This issue has broken all of our NPM builds and we are no longer able to run through whitesource.  Can you confirm/comment/fix?

**Comment by dnorth98** [comment]
+1.  This has broken all our npm builds too.  What I'm hoping to do as a workaround is use n to temporarily set the node version, scan with whitesource and then switch back.  ugh

**Comment by annarozin** [comment]
We've noticed your post and have opened a support case to address the issue.
We'll keep you informed of a resolution through our Support channel.

**Comment by dnorth98** [comment]
Just some more info:

Using node 7.10 and Whitesource scanner 17.12.4 (latest as of this writing) - scanning works
Using node 8.x (tested 8.6, 8.7 and 8.9 personally) and Whitesource scanner 17.12.4 - auth error

So it looks like a generic problem with node 8.x (as @anwalkers noted)
