### ISSUE TITLE
registryPackageUrl can be undefined leading to error

### ISSUE THREAD

**Issue by jrust** [whitesource/npm-plugin#22]
Using the latest version of the plugin (17.12.4) and node 8.9.3 whitesource fails with the following error:

```
OK: Building dependencies report
C:\app\node_modules\whitesource\bin\ws_node_report_builder.js:289
                                                if (registryPackageUrl.match(regexToFindIfPackageNameInclude) == null) {
                                                                       ^

TypeError: Cannot read property 'match' of undefined
```

The reason is that the `resolved` variable is a github url of `github:seeq12/angular-editable-text#e2cdfc86532f5d47697944d8959d566c6594124d` and the regex to find the registry (`new RegExp("(.*)\/[^A-Za-z0-9\/].*");`) does not match.  Seems that changing the if condition to `if (!registryPackageUrl || registryPackageUrl.match(regexToFindIfPackageNameInclude) == null) {` would solve the problem.

**Comment by puncha** [comment]
I have the following dependencies failing the white-source plugin:
` "some_service": "git+https://username:token@git.mycompany.com/OrgName/some_service.git#v3.0.0",

**Comment by srosenthal** [comment]
It looks like this was "fixed" by https://github.com/whitesource/npm-plugin/pull/23

Note: "fixed" means WhiteSource will ignore the dependencies it can't parse. That's certainly better than crashing, but it will leave a few holes in our WhiteSource analysis.

**Comment by juliorenner** [comment]
I am facing the same issue in version 18.3.1

**Comment by MitchK** [comment]
This is still an issue with the latest release:
```
npm run whitesource

> mypackage@0.1.0 whitesource /Users/user/path/mypackage
> whitesource run

OK: Config file is located in: ./whitesource.config.json
OK: Running whitesource V18.10.2-1...
OK: Done calculation dependencies!
OK: Building dependencies report
/Users/user/path/mypackage/node_modules/whitesource/bin/ws_node_report_builder.js:348
                        if (registryPackageUrl.match(regexToFindIfPackageNameInclude) == null) {
                                               ^

TypeError: Cannot read property 'match' of undefined
    at Object.WsNodeReportBuilder.traverseLsJson (/Users/user/path/mypackage/node_modules/whitesource/bin/ws_node_report_builder.js:348:48)
    at /Users/user/path/mypackage/node_modules/whitesource/bin/whitesource.js:547:37
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```

**Comment by kmackinnon** [comment]
Are there any workarounds? Is there a version of the plugin for which this isn't a defect?

**Comment by dfmoyer** [comment]
I ran into this issue as well. What I discovered was the pckage.json file had a dependency that did not conform to the regex in line 342 so attempts to parse did not work. By changing the Regex to 
        RegExp("(.*)\/*[^A-Za-z0-9\-\/].*")
we were able to clear this error and complete the scan successfully.

**Comment by alpanachaphalkar** [comment]
> I have the following dependencies failing the white-source plugin:
> ` "some_service": "git+https://username:token@git.mycompany.com/OrgName/some_service.git#v3.0.0"`

Hi @puncha , I am facing the exact problem.. whitesource fails if package.json contains the private git repo as dependency. Have you find the solution?

**Comment by alpanachaphalkar** [comment]
> Using the latest version of the plugin (17.12.4) and node 8.9.3 whitesource fails with the following error:
> 
> ```
> OK: Building dependencies report
> C:\app\node_modules\whitesource\bin\ws_node_report_builder.js:289
>                                                 if (registryPackageUrl.match(regexToFindIfPackageNameInclude) == null) {
>                                                                        ^
> 
> TypeError: Cannot read property 'match' of undefined
> ```
> 
> The reason is that the `resolved` variable is a github url of `github:seeq12/angular-editable-text#e2cdfc86532f5d47697944d8959d566c6594124d` and the regex to find the registry (`new RegExp("(.*)\/[^A-Za-z0-9\/].*");`) does not match. Seems that changing the if condition to `if (!registryPackageUrl || registryPackageUrl.match(regexToFindIfPackageNameInclude) == null) {` would solve the problem.

The solution provided worked! Thanks :) I hope whitesource fixes this in upcoming version. Currently, I had to create the whitesource docker image with this fix and run the scan with the docker image and it works 😀
